### ISSUE TITLE
source.startsWith is not a function

### ISSUE THREAD

**Issue by predragnikolic** [johnsoncodehk/vite-plugin-vue-component-preview#4]
# Steps to reproduce

1. run `npm run dev`
2. visit this link:
http://localhost:5173/__preview/src/components/HelloWorld.vue
3. try to modify code between the `<preview lang="md">...</preview>` tags in /src/components/HelloWorld.vue

Expected behavior:
No error to be thrown

Actual behavior:
This error is thrown:
```
source.startsWith is not a function
    at startsWith (/Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1573:19)
    at isEnd (/Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1604:17)
    at parseChildren (/Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:880:13)
    at Object.baseParse (/Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:852:23)
    at Object.parse (/Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3114:25)
    at Object.parse (/Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:5048:26)
    at createDescriptor (file:///Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vitejs/plugin-vue/dist/index.mjs:62:43)
    at handleHotUpdate (file:///Users/codetribe/Documents/sandbox/my-vue-app/node_modules/@vitejs/plugin-vue/dist/index.mjs:2011:26)
    at async handleHMRUpdate (file:///Users/codetribe/Documents/sandbox/my-vue-app/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:37660:37)
    at async FSWatcher.<anonymous> (file:///Users/codetribe/Documents/sandbox/my-vue-app/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:59317:17
 ```

Here is a repo, to reproduce the error.
https://github.com/predragnikolic/vite-preview-bug

**Comment by predragnikolic** [comment]
Thanks for the ultra quick fix, 
can verify that this is fixed! :)
